
version: '3.1'
services:
  bookmedik:
    container_name: bookmedik
    image: usuario/bookmedik:v1
    restart: always
    environment:
      DATABASE_USER: bookmedik
      DATABASE_PASSWORD: bookmedik
      DATABASE_HOST: mariadb
      DB_NAME: bookmedik
    ports:
      - 8081:80
    depends_on:
      - db
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: bookmedik
      MARIADB_USER: bookmedik
      MARIADB_PASSWORD: bookmedik
    volumes:
      - mariadb_data:/var/lib/mysql
volumes:
    mariadb_data:
